import NavBar from "@/components/layout/NavBar"
import '../styles/app/index.scss'

export const metadata = {
  title: 'Bein-Media',
  description: 'Generated by karim aldeen',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/app/logo.png" sizes="any" />
      <link rel="manifest" href="/manifest.json"/>

        <title>Bein Media Test</title>
      <body>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
